- name: install nrpe repos
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - tree
      - wget
- name: install nrpe
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - nrpe
      - nagios-plugins-users
      - nagios-plugins-load
      - nagios-plugins-swap
      - nagios-plugins-disk
      - nagios-plugins-procs

- lineinfile:
    path: /etc/nagios/nrpe.cfg
    regexp: '^server_address'
    insertafter: '^server_address='
    line: 'server_address=10.0.0.6'
- name: Restart service nrpe, in all cases
  service:
    name: nrpe
    state: restarted
    enabled: yes
